# Site settings
title: Spencer Dickson
description: 'Portfolio of Projects'
url: 'captcayde.github.io'
# baseurl: '/jekyll-uno'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Spencer Dickson'
  email: spencerjdickson@gmail.com
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  github_username:  CaptCayde
  linkedin_username:  spencer-dickson-326464196
  # rss:

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
